- name: Destroy Infracture Resources
  hosts: all
  tasks:
    # Destroy s3 bucket
    - s3_bucket:
        name: verint-bucket
        state: absent
        force: yes
    # Postgres RDS DB
    - rds:
        command: delete
        region: us-east-2
        instance_name: verint-db
    # Destroy DynamoDB Table
    - dynamodb_table:
        name: Music
        region: us-east-2
        state: absent
